default_language_version:
  # force all unspecified python hooks to run python3
  python: python3.8
repos:
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.6.3
  hooks:
    - id: nbqa-black
    - id: nbqa-pyupgrade
      args: ["--py38-plus"]
    - id: nbqa-isort
      args: ["--float-to-top"]
